services:
  - type: worker
    name: cezura-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cezura_bot.py
    pythonVersion: 3.10
    envVars:
      - key: API_TOKEN
        sync: false
