services:
  - type: worker
    name: cezura
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cezura_bot.py
    envVars:
      - key: API_TOKEN
        sync: false
    pythonVersion: 3.10.13
